<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.opentmf.client</groupId>
    <artifactId>opentmf-v4-clients</artifactId>
    <version>1.1.3-SNAPSHOT</version>
  </parent>

  <artifactId>opentmf-641-v4-client</artifactId>
  <name>opentmf-641-v4-client</name>

  <description>
    OpenTmf 641 V4 Client (Service Ordering)
  </description>

  <properties>
    <opentmf-641-v4-model.version>4.1.0.5</opentmf-641-v4-model.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.opentmf.model</groupId>
      <artifactId>opentmf-641-v4-model</artifactId>
      <version>${opentmf-641-v4-model.version}</version>
    </dependency>
  </dependencies>

</project>
