<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.pia.commons</groupId>
		<artifactId>tmf-v4-clients</artifactId>
		<version>1.0.1</version>
	</parent>
	<artifactId>tmf-client-common</artifactId>

	<properties>
		<tmf-638-model.version>4.0.0.1</tmf-638-model.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-commons</artifactId>
		</dependency>
		<dependency>
			<groupId>com.pia.commons</groupId>
			<artifactId>tmf-common-model</artifactId>
			<version>${tmf-common-model.version}</version>
		</dependency>
		<dependency>
			<groupId>com.pia.commons</groupId>
			<artifactId>pia-webclients-common</artifactId>
			<version>${pia-webclients.version}</version>
		</dependency>
		<dependency>
			<groupId>com.github.java-json-tools</groupId>
			<artifactId>json-patch</artifactId>
			<version>${json-patch.version}</version>
		</dependency>

		<!-- Optional Dependencies -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-configuration-processor</artifactId>
			<optional>true</optional>
		</dependency>

		<!-- SolutionHub Library TEST dependencies -->
		<dependency>
			<groupId>com.pia.commons</groupId>
			<artifactId>tmf-638-model</artifactId>
			<version>${tmf-638-model.version}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

</project>
