<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.pia.commons</groupId>
		<artifactId>tmf-v4-clients</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</parent>

	<artifactId>tmf-638-client</artifactId>

	<properties>
		<tmf-638-model.version>4.0.0.1</tmf-638-model.version>
		<dnext-tmf-638-model.version>4.0.0.1</dnext-tmf-638-model.version>
	</properties>

	<dependencies>

		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>tmf-client-common</artifactId>
			<version>${project.version}</version>
		</dependency>

		<!-- SolutionHub Library dependencies -->
		<dependency>
			<groupId>com.pia.commons</groupId>
			<artifactId>tmf-638-model</artifactId>
			<version>${tmf-638-model.version}</version>
		</dependency>

		<!-- Test Dependencies -->
		<dependency>
			<groupId>com.pia.commons</groupId>
			<artifactId>dnext-tmf-638-model</artifactId>
			<version>${dnext-tmf-638-model.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>tmf-client-common</artifactId>
			<version>${project.version}</version>
			<classifier>tests</classifier>
			<type>test-jar</type>
			<scope>test</scope>
		</dependency>

	</dependencies>

</project>
